apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-observability-oss
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-observability-oss
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This Crossplane configuration for Kubernetes and Data Services
      is a starting point to observe your own internal cloud.

    meta.crossplane.io/readme: |
      This Crossplane `Configuration` for Kubernetes and Data Services
      is a starting point to observe your own internal cloud.
      It provides platform APIs to provision observability software to
      infer the platform performance from metrics, and later also possibly
      from logs and traces.

      To learn more checkout the [GitHub repo](https://github.com/upbound/configuration-observability-oss/)
      that you can copy and customize to meet the exact needs of your organization!
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      # renovate: datasource=github-releases depName=crossplane-contrib/provider-helm
      version: "v0.16.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      # renovate: datasource=github-releases depName=crossplane-contrib/provider-kubernetes
      version: "v0.10.0"
    - provider: xpkg.upbound.io/grafana/provider-grafana
      # renovate: datasource=github-releases depName=grafana/crossplane-provider-grafana
      version : "v0.8.0"
    - function: xpkg.upbound.io/upbound/function-patch-and-transform
      # renovate: datasource=github-releases depName=upbound/function-patch-and-transform
      version: "v0.2.1"
