apiVersion: meta.dev.upbound.io/v2alpha1
kind: Project
metadata:
  name: configuration-observability-oss
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.upbound.io/upbound/provider-helm
    version: v1
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.upbound.io/upbound/provider-kubernetes
    version: v1
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.upbound.io/grafana/provider-grafana
    version: v0.40.0
  - apiVersion: pkg.crossplane.io/v1
    kind: Function
    package: xpkg.upbound.io/crossplane-contrib/function-auto-ready
    version: '>=v0.4.0'
  description: A Crossplane Observability Reference Configuration For Open Source
    Software Integrations
  license: Apache-2.0
  maintainer: Upbound <support@upbound.io>
  readme: |
    Configuration to Set Up Crossplane, Provider and Resource Observability with open source software integrations such as Prometheus and Grafana.
  repository: xpkg.upbound.io/upbound/configuration-observability-oss
  source: github.com/upbound/configuration-observability-oss
