{
 "title": "Crossplane Top Level View",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "claim_namespace",
    "label": "Claim Namespace",
    "query": {
     "query": "kubernetes_crossplane_io_Object_v1alpha1_labels"
    }
   },
   {
    "name": "claim_name",
    "label": "Claim Name",
    "query": {
     "query": "kubernetes_crossplane_io_Object_v1alpha1_labels{label_crossplane_io_claim_namespace=\"$claim_namespace\"}"
    }
   },
   {
    "name": "composite_name",
    "label": "Composite Name",
    "query": {
     "query": "kubernetes_crossplane_io_Object_v1alpha1_labels{label_crossplane_io_claim_name=\"$claim_name\"}"
    }
   },
   { "name": "synced_status", "label": "Synced Status", "query": "true, false, other\n" },
   { "name": "ready_status", "label": "Ready Status", "query": "true, false, other" },
   { "name": "quantile", "label": "Quantile", "query": "0.5,0.75,0.9,0.95,0.99,100" },
   {
    "name": "group",
    "label": "group",
    "query": {
     "query": "query_result(upjet_resource_ttr_bucket)"
    }
   },
   {
    "name": "version",
    "label": "version",
    "query": {
     "query": "query_result(upjet_resource_ttr_bucket{group=\"$group\"})"
    }
   },
   {
    "name": "kind",
    "label": "kind",
    "query": {
     "query": "query_result(upjet_resource_ttr_bucket{group=\"$group\"})"
    }
   },
   {
    "name": "le",
    "label": "le",
    "query": {
     "query": "upjet_resource_ttr_bucket{group=\"$group\",kind=\"$kind\",version=\"$version\"}"
    }
   },
   { "name": "interval", "label": "Interval", "query": "2m, 5m, 10m" },
   {
    "name": "provider_namespace",
    "label": "Provider Namespace",
    "query": "crossplane-system,upbound-system"
   },
   {
    "name": "cluster_metric_samples",
    "label": "Cluster Metric Samples",
    "query": {
     "query": "metrics_crossplane_io_ClusterMetric_v1"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resource Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Managed Resources",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tf_upbound_io_Workspace_v1beta1) + sum(tf_upbound_io_ProviderConfig_v1beta1) + sum(kubernetes_crossplane_io_Object_v1alpha1) + sum(kms_aws_upbound_io_Alias_v1beta1) + sum(lambda_aws_upbound_io_Invocation_v1beta1) + sum(rds_aws_upbound_io_ClusterParameterGroup_v1beta1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Managed Resources In Sync",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tf_upbound_io_Workspace_v1beta1_synced) + sum(tf_upbound_io_ProviderConfig_v1beta1_synced) + sum(kubernetes_crossplane_io_Object_v1alpha1_synced) + sum(kms_aws_upbound_io_Alias_v1beta1_synced) + sum(lambda_aws_upbound_io_Invocation_v1beta1_synced) + sum(rds_aws_upbound_io_ClusterParameterGroup_v1beta1_synced)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Managed Resources Ready",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tf_upbound_io_Workspace_v1beta1_ready) + sum(tf_upbound_io_ProviderConfig_v1beta1_ready) + sum(kubernetes_crossplane_io_Object_v1alpha1_ready) + sum(kms_aws_upbound_io_Alias_v1beta1_ready) + sum(lambda_aws_upbound_io_Invocation_v1beta1_ready) + sum(rds_aws_upbound_io_ClusterParameterGroup_v1beta1_ready)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Extensions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(apiextensions_crossplane_io_CompositeResourceDefinition_v1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Extensions in Sync",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(apiextensions_crossplane_io_CompositeResourceDefinition_v1_synced)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Extensions Ready",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(apiextensions_crossplane_io_CompositeResourceDefinition_v1_ready)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Providers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pkg_crossplane_io_ProviderRevision_v1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$group/$version $kind TTR Count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upjet_resource_ttr_count{group=\"$group\",version=\"$version\",kind=\"$kind\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$group/$version $kind  TTR Sum",
   "type": "gauge",
   "description": "TTR Sum in Minutes.",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upjet_resource_ttr_sum{group=\"$group\",version=\"$version\",kind=\"$kind\"}/60",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "$group/$version $kind Time To Readiness in Seconds",
   "type": "timeseries",
   "description": "Preferred query:\nhistogram_quantile($quantile, sum(rate(upjet_resource_ttr_bucket{group=\"$group\",version=\"$version\",kind=\"$kind\"}[$interval])) by (le))",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "upjet_resource_ttr_bucket{group=\"$group\",version=\"$version\",kind=\"$kind\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$group/$version $kind Time TTR Histogram in Seconds",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(upjet_resource_ttr_bucket{group=\"$group\",version=\"$version\",kind=\"$kind\"}[$interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } }
 ]
}