{
 "title": "Crossplane X-Metrics",
 "description": "Claim Status Related Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "claim_name",
    "label": "Claim Name",
    "query": {
     "query": "kubernetes_crossplane_io_Object_v1alpha1_labels"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of MRs by Control Plane",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubernetes_crossplane_io_Object_v1alpha1_info > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Synced MRs per Claim",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubernetes_crossplane_io_Object_v1alpha1_synced{name=~\"$claim_name.*\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Ready MRs per Claim",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubernetes_crossplane_io_Object_v1alpha1_ready{name=~\"$claim_name.*\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Crossplane.io Object v1alpha1 Synced",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "kubernetes_crossplane_io_Object_v1alpha1_synced{name=~\"$claim_name.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Crossplane.io Object v1alpha1 Synched Time",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 13, "x": 10, "y": 4 },
   "targets": [
    {
     "expr": "kubernetes_crossplane_io_Object_v1alpha1_synced_time{name=~\"$claim_name.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Crossplane.io Object v1alpha1 Ready",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "kubernetes_crossplane_io_Object_v1alpha1_ready{name=~\"$claim_name.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Crossplane.io Object v1alpha1 Ready Time",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 13, "x": 10, "y": 13 },
   "targets": [
    {
     "expr": "kubernetes_crossplane_io_Object_v1alpha1_ready_time{name=~\"$claim_name.*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}