apiVersion: observe.platform.upbound.io/v1alpha1
kind: Oss
metadata:
  name: test-oss
spec:
  parameters:
    id: test-cluster
    operators:
      prometheus:
        version: "79.1.1"
    managementPolicies: ["*"]