{
 "title": "Crossplane Managed Resources",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Upjet Resource TTR Bucket 50% percentile",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(upjet_resource_ttr_bucket{namespace=\"upbound-system\"}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upjet Resource TTR Bucket 95% percentile",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(upjet_resource_ttr_bucket{namespace=\"upbound-system\"}[2m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upjet Resource TTR Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(upjet_resource_ttr_count{namespace=\"upbound-system\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upjet Resource TTR Bucket 99% percentile",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(upjet_resource_ttr_bucket{namespace=\"upbound-system\"}[2m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upjet Resource TTR Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(upjet_resource_ttr_sum{namespace=\"upbound-system\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upjet Terraform CLI Duration Bucket",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(upjet_terraform_cli_duration_bucket{namespace=\"upbound-system\"}[2m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upjet Terraform CLI Invocatios",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "upjet_terraform_active_cli_invocations{namespace=\"upbound-system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Terraform Running Processes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "upjet_terraform_running_processes{namespace=\"upbound-system\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}