{
 "title": "Crossplane",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Rest Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rest Client Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "rate(rest_client_requests_total[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Containeer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Starts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "kubelet_started_containers_total{}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Go",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go Memstats Alloc Bytes Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(go_memstats_alloc_bytes_total[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Go Memstats Alloc Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      { "expr": "go_memstats_alloc_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      { "expr": "go_goroutines", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Workqueue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workqueue Adds Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "rate(workqueue_adds_total{namespace=\"upbound-system\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Resident Memory Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Process  Start Time Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      { "expr": "process_start_time_seconds", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Process CPU Seconds Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Certwatcher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Certwatcher Read Certificate Errors Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "certwatcher_read_certificate_errors_total",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Certwatcher Read Certificates Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "certwatcher_read_certificate_total",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Controller Runtime Webhook Requests Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "rate(controller_runtime_webhook_requests_total[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Controller Runtime Reconcile Errors Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "rate(controller_runtime_reconcile_errors_total{namespace=\"upbound-system\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Controller Runtime Max Concurrent Reconciles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "controller_runtime_max_concurrent_reconciles{namespace=\"upbound-system\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Controller Runtime Reconcile Time Seconds Bucket",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(controller_runtime_reconcile_time_seconds_bucket[5m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Controller Runtime Reconcile Time Seconds Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "rate(controller_runtime_reconcile_time_seconds_count[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Controller Runtime Reconcile Time Seconds Sum",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "rate(controller_runtime_reconcile_time_seconds_sum{namespace=\"upbound-system\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Controller Runtime Reconcile Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "rate(controller_runtime_reconcile_total{namespace=\"upbound-system\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}