{
 "title": "Crossplane Managed Resources",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "crossplane-system, upbound-system"
   },
   { "name": "quantile", "query": "0.5, 0.95, 0.99" },
   { "name": "interval", "query": "2m,5m,10m" },
   {
    "name": "group",
    "query": {
     "query": "query_result(upjet_resource_ttr_bucket)"
    }
   },
   {
    "name": "kind",
    "label": "Kind",
    "query": {
     "query": "query_result(upjet_resource_ttr_bucket)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "query_result(upjet_resource_ttr_bucket)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CRD Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(apiextensions_openapi_v3_regeneration_count{crd=~\".*.(upbound.io|crossplane.io)\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upjet Resource TTR Bucket",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by(le) (rate(upjet_resource_ttr_bucket{namespace=\"$namespace\",group=\"$group\"}[$interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Terraform Running Processes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "upjet_terraform_running_processes{namespace=\"$namespace\",container=\"$container\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upjet Terraform CLI Duration Bucket",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(upjet_terraform_cli_duration_bucket{namespace=\"$namespace\"}[$interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upjet Resource TTR Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(upjet_resource_ttr_sum{namespace=\"$namespace\", group=\"$group\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upjet Resource TTR Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(upjet_resource_ttr_count{namespace=\"$namespace\",container=\"$container\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upjet Terraform CLI Invocatios",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "upjet_terraform_active_cli_invocations{namespace=\"$namespace\",group=\"$group\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}