{
 "title": "Crossplane Health",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Crossplane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Aggregation Unavailable",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "aggregator_unavailable_apiservice{name=~\".upbound.io\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate For Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum without (pod, kubernetes_pod_name, service)(increase(controller_runtime_reconcile_total{result=\"error\", controller=~\"(claim.*|offered.*|composite.*|defined.*|packages.*|revisions.*)\"}[2m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_admission_controller_admission_duration_seconds_bucket{namespace=\"default\"} [2m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate For Time To Reconcile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum without (pod, kubernetes_pod_name, service)(increase(controller_runtime_reconcile_total{namespace=\"$namespace\", result=\"success\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workqueue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "workqueue_depth{namespace=\"$namespace\", name=~\".*.(crossplane.io|upbound.io)\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Controller Reconciliation Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum without(pod, instance, endpoint, job, exported_instance)(increase(controller_runtime_reconcile_time_seconds_sum{namespace=\"$namespace\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Service Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum without (pod) (label_replace(up, \"pod\", \"$1\", \"job\", \"(.*)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum without(service, uid)(kube_pod_container_status_running{namespace=\"upbound-system\"}) >= 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Managed Resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(kube_managedresource_uid{namespace=\"$namespace\"}) by (customresource_group, customresource_kind, customresource_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Custom Resource Definition",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "count(apiextensions_openapi_v3_regeneration_count{namespace=\"default\", crd=~\".*.(upbound.io|crossplane.io)\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\"}[$__rate_interval])) by (container) / sum(increase(container_cpu_cfs_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\"}[2m])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}