apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: osss.observe.platform.upbound.io
spec:
  compositeTypeRef:
    apiVersion: observe.platform.upbound.io/v1alpha1
    kind: Oss
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-configuration-observability-osscompose-oss
    step: Compose-Oss-Resources
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: auto-ready
