apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xosss.observe.platform.upbound.io
spec:
  compositeTypeRef:
    apiVersion: observe.platform.upbound.io/v1alpha1
    kind: XOss

  patchSets:
    - name: common
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - fromFieldPath: spec.parameters.id
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "configuration-observability-%s"

  resources:
    - name: podMonitorCrossplaneRbacManager
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: monitoring.coreos.com/v1
              kind: PodMonitor
              metadata:
                name: crossplane-rbac-manager
                namespace: upbound-system
                labels:
                  app: crossplane-rbac-manager
              spec:
                selector:
                  matchLabels:
                    app: crossplane-rbac-manager
                podMetricsEndpoints:
                - port: metrics
      patches:
        - type: PatchSet
          patchSetName: common

    - name: podMonitorCrossplane
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: monitoring.coreos.com/v1
              kind: PodMonitor
              metadata:
                name: crossplane
                namespace: upbound-system
                labels:
                  app: crossplane
              spec:
                selector:
                  matchLabels:
                    app: crossplane
                podMetricsEndpoints:
                - port: metrics
      patches:
        - type: PatchSet
          patchSetName: common

    - name: podMonitorCrossplaneProviders
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: monitoring.coreos.com/v1
              kind: PodMonitor
              metadata:
                name: crossplane-providers
                namespace: upbound-system
                labels:
                  app: crossplane-providers
              spec:
                selector:
                  matchLabels:
                    app: crossplane-providers
                podMetricsEndpoints:
                - port: http-prom
      patches:
        - type: PatchSet
          patchSetName: common

    - name: podMonitorXmetrics
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: monitoring.coreos.com/v1
              kind: PodMonitor
              metadata:
                name: x-metrics
                namespace: x-metrics
                labels:
                  app: x-metrics
              spec:
                selector:
                  matchLabels:
                    app: x-metrics
                podMetricsEndpoints:
                  - port: http-prom
                    path: /x-metrics
      patches:
        - type: PatchSet
          patchSetName: common

    - name: releasePrometheus
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        spec:
          rollbackLimit: 3
          forProvider:
            namespace: operators
            chart:
              name: kube-prometheus-stack
              repository: https://prometheus-community.github.io/helm-charts
              version: "52.1.0"
            values:
              prometheus:
                prometheusSpec:
                  serviceMonitorSelectorNilUsesHelmValues: false
                  podMonitorSelectorNilUsesHelmValues: false
                  probeSelectorNilUsesHelmValues: false
                  ruleSelectorNilUsesHelmValues: false
      patches:
        - type: PatchSet
          patchSetName: common
        - fromFieldPath: spec.parameters.id
          toFieldPath: metadata.name
        - fromFieldPath: spec.parameters.id
          toFieldPath: metadata.annotations[crossplane.io/external-name]
          transforms:
            - type: string
              string:
                fmt: "configuration-observability-%s"
        - fromFieldPath: metadata.labels
          toFieldPath: metadata.labels
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.parameters.operators.prometheus.version
          toFieldPath: spec.forProvider.chart.version
