apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xosss.observe.platform.upbound.io
spec:
  compositeTypeRef:
    apiVersion: observe.platform.upbound.io/v1alpha1
    kind: XOss
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-configuration-observability-ossxoss
    step: xoss
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: auto-ready
