apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: osss.observe.platform.upbound.io
spec:
  scope: Namespaced
  defaultCompositeDeletePolicy: Foreground
  group: observe.platform.upbound.io
  names:
    kind: Oss
    plural: osss
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  description: Monitoring configuration parameters.
                  properties:
                    id:
                      type: string
                      description: ID of this Cluster to enable Monitoring with OSS Prometheus and Grafana
                    operators:
                      type: object
                      description: Operators parameters.
                      properties:
                        prometheus:
                          type: object
                          description: Prometheus operator parameters.
                          properties:
                            version:
                              type: string
                              description: Prometheus chart version.
                    managementPolicies:
                      description: ManagementPolicies for the RDS resources. Defaults to ["*"] which includes all operations (Create, Observe, Update, Delete). To orphan resources on deletion, use ["Create", "Observe", "Update"].
                      type: array
                      items:
                        type: string
                        enum:
                          - "*"
                          - Create
                          - Observe
                          - Update
                          - Delete
                      default: ["*"]                      
                  required:
                    - id
              required:
                - parameters
            status:
              type: object
              properties:
                backup:
                  description: Freeform field containing status information for uxp-datadog
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
